name: aiida-qe-demo
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - aiida-core~=2.0.4
  - aiida-quantumespresso.meta=4
  - qe=7
  - xmltodict
  - jupyterlab=3
  - jupyterlab-myst
  - cryptography>=37.0.4  # lower gives wrong link to openssl
  # documentation
  - myst-parser>=0.18.1
  - myst-nb
  - sphinx-design
  - sphinx-book-theme
  - sphinx-subfigure>=0.2.4
  - pip:
    # can use conda when version merged
    - myst-nb>=0.17.0
