name: aiida-qe-demo
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - aiida-core~=2.0.4
  - aiida-quantumespresso.meta=4
  - qe=7
  - xmltodict
  - jupyterlab=3
  - jupyterlab-myst
  - cryptography>=37.0.4  # lower gives wrong link to openssl
  - nglview=3
  # see: https://github.com/nglviewer/nglview/issues/1032
  - ipywidgets<8
